---

- name: Setup playbook fact
  block:
    - name: Gather playbook version
      block:
        - name: Seach git repository
          ansible.builtin.stat:
            path: "{{ playbook_fact_git_search_path_item }}/.git"
          register: playbook_fact_search_git_result
          when: not playbook_fact_search_git_result.stat.exists | default(false)
          loop: >-
            {{ lookup("template", "git_search_paths.yml.j2") | from_yaml }}
          loop_control:
            loop_var: playbook_fact_git_search_path_item
          delegate_to: localhost
          become: no

        - name: Get git project name
          ansible.builtin.command: >-
            git config --get remote.{{ playbook_fact_remote_item }}.url
          args:
            chdir: "{{ playbook_fact_git_project_path }}"
            warn: no
          register: playbook_fact_get_remote_result
          changed_when: no
          failed_when: no
          loop: "{{ playbook_fact_remote_list }}"
          loop_control:
            loop_var: playbook_fact_remote_item
          delegate_to: localhost
          become: no

        - name: Gather git repository version
          ansible.builtin.command: git describe --tags
          args:
            chdir: "{{ playbook_fact_git_project_path }}"
            warn: no
          register: playbook_fact_get_version_result
          failed_when: no
          changed_when: no
          delegate_to: localhost
          become: no
      vars:
        ansible_connection: local

    - name: Get playbook file
      playbook_fact_get_file:
      register: playbook_fact_get_file_result

    - name: Setup playbook fact
      ansible.builtin.set_fact:
        playbook_info: >-
          {{ lookup("template", "playbook_info.fact.j2") | from_yaml }}

    - name: Create local facts directory
      ansible.builtin.file:
        path: "{{ playbook_fact_project_dir }}"
        state: directory
        mode: 0755

    - name: Configure main playbooks local fact
      ansible.builtin.template:
        src: playbooks_info.sh.fact.j2
        dest: "{{ playbook_fact_d_dir }}/playbooks_info.fact"
        mode: 0755

    - name: Configure playbook local fact
      ansible.builtin.template:
        src: playbook_info.fact.j2
        dest: "{{ playbook_fact_file_path }}"
        owner: root
        group: root
        mode: 0644

  vars:
    playbook_fact_git_project_path: >-
      {{ (playbook_fact_search_git_result.results
          | selectattr("stat", "defined")
          | selectattr("stat.exists", "equalto", true)
          | list
          | first).stat.path
         | dirname }}

    playbook_fact_file: "{{ playbook_fact_get_file_result.file | basename }}"

  tags:
    - role::playbook_fact
